[palettes.tokyonight]
bg      = "#272932"
fg      = "#EEE9E7"
bgdim   = "#09090B"
accent  = "#FDF500"
black   = "#09090B"
red     = "#CC0000"
green   = "#1AC5B0"
yellow  = "#FDF500"
blue    = "#7dcfff"
magenta = "#E455AE"
cyan    = "#37EBF3"
white   = "#EEE9E7"
