[palettes.tokyonight]
bg      = "#24273a"
fg      = "#cad3f5"
bgdim   = "#181926"
accent  = "#f5bde6"
black   = "#181926"
red     = "#ed8796"
green   = "#a6da95"
yellow  = "#eed49f"
blue    = "#8aadf4"
magenta = "#f5bde6"
cyan    = "#7dc4e4"
white   = "#cad3f5"
