[palettes.tokyonight]
bg      = "#2E3440"
fg      = "#D8DEE9"
bgdim   = "#3B4252"
accent  = "#88C0D0"
black   = "#3B4252"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#88C0D0"
white   = "#E5E9F0"
