# ~/.config/starship.toml
palette = "tokyonight"

# Master prompt layout
format = "[ $os ](bg:bgdim fg:accent)[](fg:bgdim bg:white)[ $username ](fg:black bg:white)[](fg:white bg:bgdim)[ $directory ](fg:fg bg:bgdim)[$git_branch$git_status](fg:fg bg:bgdim)[$golang](fg:fg bg:bgdim)[$python](fg:fg bg:bgdim)[$lua](fg:fg bg:bgdim)[$terraform](fg:fg bg:bgdim)[$kubernetes](fg:fg bg:bgdim)[](fg:bgdim)[$fill](fg:fg)[](fg:bgdim)[$status](fg:fg bg:bgdim)[$conda](fg:yellow bg:bgdim)[$nix_shell](fg:blue bg:bgdim)[$character](fg:fg bg:bgdim) "

# Continuation prompt for wrapped commands
continuation_prompt = "      [│](fg:blue)  "

# --- OS ----------------------------------------------------------------------
[os]
format = "$symbol"
style = "bold fg:accent"
disabled = false

[os.symbols]
Arch = ""
EndeavourOS = " "
NixOS = ""

# --- Username ----------------------------------------------------------------
[username]
style_user = "black bold"
style_root = "red bold"
format = "$user"
disabled = false
show_always = true

# --- Directory ---------------------------------------------------------------
[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
format = "$path $read_only"
home_symbol = " ~"
read_only = ""
read_only_style = "red"

# --- Git ---------------------------------------------------------------------
[git_branch]
symbol = " "
truncation_length = 15
truncation_symbol = ""
style = "red"
format = " [$symbol$branch](fg:red bg:bgdim)"

[git_status]
conflicted = " =$count"
ahead = " ⇡$count"
behind = " ⇣$count"
diverged = " ⇕$count"
up_to_date = "✓"
untracked = " ?$count"
stashed = " $$count"
renamed = " »$count"
deleted = " X$count"
staged = " +$count"
modified = " !$count"
format = "[$all_status](fg:red bg:bgdim) "

# --- Conda / Python envs -----------------------------------------------------
[conda]
symbol = ""
style = "yellow"
format = " [$symbol $environment](fg:yellow bg:bgdim) "
ignore_base = false

# --- AWS ---------------------------------------------------------------------
[aws]
symbol = ""
format = " [$symbol $profile](fg:yellow bg:bgdim) "

# --- Kubernetes --------------------------------------------------------------
[kubernetes]
symbol = ""
format = " [$symbol $context](fg:blue bg:bgdim) "

# --- Languages ---------------------------------------------------------------
[lua]
symbol = ""
format = " [$symbol $version](fg:blue bg:bgdim) "

[golang]
symbol = ""
format = " [$symbol $version](fg:blue bg:bgdim) "

[python]
symbol = ""
format = " [$symbol $version $virtualenv ](fg:yellow bg:bgdim) "

[terraform]
symbol = ""
format = " [$symbol $version](fg:blue bg:bgdim) "

# --- Fill (spacer line) ------------------------------------------------------
[fill]
symbol = "─"
style = "bold fg:fg"

# --- Status ------------------------------------------------------------------
[status]
symbol = "[](fg:red bg:bgdim) "
success_symbol = "[](fg:green bg:bgdim) "
format = " $symbol$status "
disabled = false

# --- Nix shell ---------------------------------------------------------------
[nix_shell]
symbol = ""
format = " [$symbol $name](fg:blue bg:bgdim) "

# --- Character / prompt symbol ----------------------------------------------
[character]
format = "$symbol"

# Normal shell (success/error)
success_symbol = " [  ](fg:blue bg:bgdim)[\n ❯](fg:green)"
error_symbol   = " [  ](fg:blue bg:bgdim)[\n ❯](fg:red)"

# Vim/Vi modes — same background, mode-colored text
vimcmd_symbol             = " [  ](fg:accent bg:bgdim)[\n ❯](fg:accent)"  # command/normal
vimcmd_replace_symbol     = " [  ](fg:red bg:bgdim)[\n ❯](fg:red)"       # replace
vimcmd_replace_one_symbol = " [  ](fg:yellow bg:bgdim)[\n ❯](fg:yellow)"  # replace-one
vimcmd_visual_symbol      = " [󰈈  ](fg:magenta bg:bgdim)[\n ❯](fg:magenta)"# visual

# --- Time --------------------------------------------------------------------
[time]
disabled = false
format = "[$time](fg:blue bg:bgdim)[ ](fg:bgdim)"
time_format = "%H:%M"

[palettes.tokyonight]
bg      = "#272932"
fg      = "#EEE9E7"
bgdim   = "#09090B"
accent  = "#FDF500"
black   = "#09090B"
red     = "#CC0000"
green   = "#1AC5B0"
yellow  = "#FDF500"
blue    = "#7dcfff"
magenta = "#E455AE"
cyan    = "#37EBF3"
white   = "#EEE9E7"
